//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamBuilding
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class TeamBuildingEntities : DbContext
    {
        public TeamBuildingEntities()
            : base("name=TeamBuildingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Classes> Classes { get; set; }
        public virtual DbSet<Contacts> Contacts { get; set; }
        public virtual DbSet<LikedProjects> LikedProjects { get; set; }
        public virtual DbSet<PrjtClasses> PrjtClasses { get; set; }
        public virtual DbSet<Projects> Projects { get; set; }
        public virtual DbSet<Requests> Requests { get; set; }
        public virtual DbSet<Skills> Skills { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
